version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #   - DOCKER_HOST=tcp://docker:2375
    networks:
      - jenkins_network
    privileged: true # Это важно для использования Docker внутри контейнера

  docker:
    image: docker:dind
    container_name: docker
    networks:
      - jenkins_network
    privileged: true

volumes:
  jenkins_home:


networks:
  jenkins_network:
    driver: bridge
