pipeline {
    agent any 
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                   sh 'docker build -t imagination .'

                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    
                    sh "docker run --rm imagination ."
                }
            }
        }
    }
      post {
        always {
            script {
                echo 'Jenkins is cleaning up...after me ehhh'
                try {
                    def containers = sh(script: "docker ps -q --filter 'name=imagination'", returnStdout: true).trim()
                    if (containers) {
                        echo "Stopping containers: ${containers}"
                        sh "docker stop ${containers}"
                    }
                } catch (Exception e) {
                    echo "No running containers to stop."
                }
                try {
                    def containers = sh(script: "docker ps -a -q --filter 'name=imagination'", returnStdout: true).trim()
                    if (containers) {
                        echo "Removing containers: ${containers}"
                        sh "docker rm ${containers}"
                    }
                } catch (Exception e) {
                    echo "No containers to remove."
                }
                echo "Removing Docker images..."
                sh "docker rmi imagination || true" //only if exists
            }
        }
    }
}